//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassengerFlowDal.Utility
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DalParameter", Namespace="http://schemas.datacontract.org/2004/07/PassengerFlowDal.Utility")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PassengerFlowDal.Model.TabTimeSync))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PassengerFlowDal.Model.TabTimeSync[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PassengerFlowDal.Model.TabCurData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PassengerFlowDal.Model.TabCurData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PassengerFlowDal.Model.TabHistoryData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PassengerFlowDal.Model.TabHistoryData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PassengerFlowDal.Utility.BusinessType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(int[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    public partial class DalParameter : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private object BusinessObjectField;
        
        private PassengerFlowDal.Utility.BusinessType BusinessTypeField;
        
        private string TerminalIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object BusinessObject
        {
            get
            {
                return this.BusinessObjectField;
            }
            set
            {
                this.BusinessObjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PassengerFlowDal.Utility.BusinessType BusinessType
        {
            get
            {
                return this.BusinessTypeField;
            }
            set
            {
                this.BusinessTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TerminalID
        {
            get
            {
                return this.TerminalIDField;
            }
            set
            {
                this.TerminalIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessType", Namespace="http://schemas.datacontract.org/2004/07/PassengerFlowDal.Utility")]
    public enum BusinessType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddCheckTime = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddData = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GetAreaInfo = 3,
    }
}
namespace PassengerFlowDal.Model
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TabTimeSync", Namespace="http://schemas.datacontract.org/2004/07/PassengerFlowDal.Model")]
    public partial class TabTimeSync : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double DeltaTimeField;
        
        private string DevMacField;
        
        private long DevTimeField;
        
        private string MemoField;
        
        private int ModuleNoField;
        
        private System.Guid ObjIDField;
        
        private System.DateTime ServerTimeField;
        
        private System.DateTime TheDateField;
        
        private byte ValidField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DeltaTime
        {
            get
            {
                return this.DeltaTimeField;
            }
            set
            {
                this.DeltaTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevMac
        {
            get
            {
                return this.DevMacField;
            }
            set
            {
                this.DevMacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DevTime
        {
            get
            {
                return this.DevTimeField;
            }
            set
            {
                this.DevTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memo
        {
            get
            {
                return this.MemoField;
            }
            set
            {
                this.MemoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModuleNo
        {
            get
            {
                return this.ModuleNoField;
            }
            set
            {
                this.ModuleNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ObjID
        {
            get
            {
                return this.ObjIDField;
            }
            set
            {
                this.ObjIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ServerTime
        {
            get
            {
                return this.ServerTimeField;
            }
            set
            {
                this.ServerTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TheDate
        {
            get
            {
                return this.TheDateField;
            }
            set
            {
                this.TheDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Valid
        {
            get
            {
                return this.ValidField;
            }
            set
            {
                this.ValidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TabCurData", Namespace="http://schemas.datacontract.org/2004/07/PassengerFlowDal.Model")]
    public partial class TabCurData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ChannelField;
        
        private string DevMacField;
        
        private long DevTimeField;
        
        private string MemoField;
        
        private int ModuleNoField;
        
        private System.Guid ObjIDField;
        
        private string PhoneMacField;
        
        private int RSSIField;
        
        private System.DateTime RealTimeField;
        
        private System.DateTime TheDateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Channel
        {
            get
            {
                return this.ChannelField;
            }
            set
            {
                this.ChannelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevMac
        {
            get
            {
                return this.DevMacField;
            }
            set
            {
                this.DevMacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DevTime
        {
            get
            {
                return this.DevTimeField;
            }
            set
            {
                this.DevTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memo
        {
            get
            {
                return this.MemoField;
            }
            set
            {
                this.MemoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModuleNo
        {
            get
            {
                return this.ModuleNoField;
            }
            set
            {
                this.ModuleNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ObjID
        {
            get
            {
                return this.ObjIDField;
            }
            set
            {
                this.ObjIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneMac
        {
            get
            {
                return this.PhoneMacField;
            }
            set
            {
                this.PhoneMacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RSSI
        {
            get
            {
                return this.RSSIField;
            }
            set
            {
                this.RSSIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RealTime
        {
            get
            {
                return this.RealTimeField;
            }
            set
            {
                this.RealTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TheDate
        {
            get
            {
                return this.TheDateField;
            }
            set
            {
                this.TheDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TabHistoryData", Namespace="http://schemas.datacontract.org/2004/07/PassengerFlowDal.Model")]
    public partial class TabHistoryData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ChannelField;
        
        private string DevMacField;
        
        private long DevTimeField;
        
        private string MemoField;
        
        private int ModuleNoField;
        
        private System.Guid ObjIDField;
        
        private string PhoneMacField;
        
        private int RSSIField;
        
        private System.DateTime RealTimeField;
        
        private System.DateTime TheDateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Channel
        {
            get
            {
                return this.ChannelField;
            }
            set
            {
                this.ChannelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevMac
        {
            get
            {
                return this.DevMacField;
            }
            set
            {
                this.DevMacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DevTime
        {
            get
            {
                return this.DevTimeField;
            }
            set
            {
                this.DevTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memo
        {
            get
            {
                return this.MemoField;
            }
            set
            {
                this.MemoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModuleNo
        {
            get
            {
                return this.ModuleNoField;
            }
            set
            {
                this.ModuleNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ObjID
        {
            get
            {
                return this.ObjIDField;
            }
            set
            {
                this.ObjIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneMac
        {
            get
            {
                return this.PhoneMacField;
            }
            set
            {
                this.PhoneMacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RSSI
        {
            get
            {
                return this.RSSIField;
            }
            set
            {
                this.RSSIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RealTime
        {
            get
            {
                return this.RealTimeField;
            }
            set
            {
                this.RealTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TheDate
        {
            get
            {
                return this.TheDateField;
            }
            set
            {
                this.TheDateField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDalSvr")]
public interface IDalSvr
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDalSvr/AddInfo", ReplyAction="http://tempuri.org/IDalSvr/AddInfoResponse")]
    void AddInfo(PassengerFlowDal.Utility.DalParameter para);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDalSvr/AddInfo", ReplyAction="http://tempuri.org/IDalSvr/AddInfoResponse")]
    System.Threading.Tasks.Task AddInfoAsync(PassengerFlowDal.Utility.DalParameter para);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDalSvr/GetInfo", ReplyAction="http://tempuri.org/IDalSvr/GetInfoResponse")]
    PassengerFlowDal.Utility.DalParameter GetInfo(PassengerFlowDal.Utility.DalParameter para);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDalSvr/GetInfo", ReplyAction="http://tempuri.org/IDalSvr/GetInfoResponse")]
    System.Threading.Tasks.Task<PassengerFlowDal.Utility.DalParameter> GetInfoAsync(PassengerFlowDal.Utility.DalParameter para);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDalSvrChannel : IDalSvr, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DalSvrClient : System.ServiceModel.ClientBase<IDalSvr>, IDalSvr
{
    
    public DalSvrClient()
    {
    }
    
    public DalSvrClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DalSvrClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DalSvrClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DalSvrClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void AddInfo(PassengerFlowDal.Utility.DalParameter para)
    {
        base.Channel.AddInfo(para);
    }
    
    public System.Threading.Tasks.Task AddInfoAsync(PassengerFlowDal.Utility.DalParameter para)
    {
        return base.Channel.AddInfoAsync(para);
    }
    
    public PassengerFlowDal.Utility.DalParameter GetInfo(PassengerFlowDal.Utility.DalParameter para)
    {
        return base.Channel.GetInfo(para);
    }
    
    public System.Threading.Tasks.Task<PassengerFlowDal.Utility.DalParameter> GetInfoAsync(PassengerFlowDal.Utility.DalParameter para)
    {
        return base.Channel.GetInfoAsync(para);
    }
}
