//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFCDal.Utility
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LFCDalParameter", Namespace="http://schemas.datacontract.org/2004/07/LFCDal.Utility")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LFCDal.Model.tCTUInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LFCDal.Model.tCTUInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LFCDal.Model.tSysRunStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LFCDal.Model.tSysRunStatus[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LFCDal.Model.vLampInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LFCDal.Model.vLampInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LFCDal.Model.tLampNewStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LFCDal.Model.tLampNewStatus[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LFCDal.Model.tPTUCurDataRec))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LFCDal.Model.tPTUCurDataRec[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LFCDal.Model.tLampTmpCtrlCfg))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LFCDal.Model.tLampTmpCtrlCfg[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LFCDal.Model.pLampTmpCtrlCfg))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LFCDal.Model.pLampTmpCtrlCfg[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LFCDal.Model.tLampWeekCtrlCfg))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LFCDal.Model.tLampWeekCtrlCfg[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LFCDal.Model.tCTUOCDayCfg))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LFCDal.Model.tCTUOCDayCfg[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LFCDal.Model.tLampHisDataRec))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LFCDal.Model.tLampHisDataRec[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LFCDal.Model.tLampGrpCfg))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LFCDal.Model.tLampGrpCfg[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LFCDal.Utility.BusinessType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(int[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    public partial class LFCDalParameter : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private object BusinessObjectField;
        
        private LFCDal.Utility.BusinessType BusinessTypeField;
        
        private string CTUIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object BusinessObject
        {
            get
            {
                return this.BusinessObjectField;
            }
            set
            {
                this.BusinessObjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LFCDal.Utility.BusinessType BusinessType
        {
            get
            {
                return this.BusinessTypeField;
            }
            set
            {
                this.BusinessTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CTUID
        {
            get
            {
                return this.CTUIDField;
            }
            set
            {
                this.CTUIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessType", Namespace="http://schemas.datacontract.org/2004/07/LFCDal.Utility")]
    public enum BusinessType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GetCtuInfo = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GetLampList = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GetSysRunStatus = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GetLampStatusByLampNo = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GetLampDataRecByLampNo = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GetLampTempCtrlCfg = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DelLampTmpCtrlCfgByNo = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DelAllLampTmpCtrlCfg = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddLampTmpCtrlCfg = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DelLampWeekCtrlCfgByWeekDay = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DelAllLampWeekCtrlCfg = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddLampWeekCtrlCfg = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GetChronologyOfToday = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GetPlanFromLampTmpCtrlCfg = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GetPlanFromLampWeekCtrlCfg = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GetMaxNoFromElecData = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SaveElecData = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GetMaxLampTmpCtrlCfgNo = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DelLampTmpCtrlCfgByCfgNo = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QueryLampTempCtrlCfg = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateLampTmpCtrlStatus = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QueryPlanFromLampWeekCtrlCfg = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SaveLampGroupCfg = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateLampGrpCfgStatus = 24,
    }
}
namespace LFCDal.Model
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tCTUInfo", Namespace="http://schemas.datacontract.org/2004/07/LFCDal.Model")]
    public partial class tCTUInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> AIClctIntvalField;
        
        private byte AutoRouteTickField;
        
        private string CTUChByteField;
        
        private byte CTUChNumField;
        
        private string CTUCommAddrField;
        
        private string CTUIDField;
        
        private string CTUMacAddrField;
        
        private string CTUNameField;
        
        private byte CTUTypeField;
        
        private string CabIDField;
        
        private System.Nullable<byte> CtrlCloseDivField;
        
        private string CtrlLineValidFlagField;
        
        private System.Nullable<int> DIClctIntvalField;
        
        private System.Nullable<byte> DeviceTypeField;
        
        private System.Nullable<byte> DiAlarmTickField;
        
        private System.Nullable<byte> DiUpdateTimeField;
        
        private byte EnergyEfficientField;
        
        private byte EnergyTimeTypeField;
        
        private string EventAutoUploadFlagField;
        
        private string EventImportanceFlagField;
        
        private string EventRecValidFlagField;
        
        private System.Nullable<byte> EveryDayCtlMarkField;
        
        private int FSMField;
        
        private System.Nullable<byte> FindPTUTickField;
        
        private System.Nullable<byte> GPRSHeartField;
        
        private System.Nullable<byte> GPRSRetryCountField;
        
        private System.Nullable<int> GPRSTimeOutField;
        
        private string GSM_IMEIField;
        
        private byte HavePTUStatusField;
        
        private System.Nullable<byte> HaveRTUField;
        
        private string IPAddressField;
        
        private string IPGatewayField;
        
        private System.Nullable<byte> IsNeedRpyMaskField;
        
        private System.Nullable<int> IsSingleLampFuncField;
        
        private string LatitudeField;
        
        private int LogPrintTickField;
        
        private string LongitudeField;
        
        private string MASKAddressField;
        
        private string MobilePhoneNoField;
        
        private System.Nullable<byte> NetworkTypeField;
        
        private byte PLCComTimerField;
        
        private System.Nullable<int> PTUCountField;
        
        private System.Nullable<byte> PTUTypeField;
        
        private System.Nullable<byte> PollingTickField;
        
        private System.Nullable<byte> PwrSaveSwitchMaxPosField;
        
        private string PwrSaveValidFlagField;
        
        private System.Nullable<byte> RouterCommErrTestIntvalField;
        
        private string SIM_IMSIField;
        
        private System.Nullable<byte> SingLampCloseClctDelayField;
        
        private System.Nullable<byte> SingLampCurrClctDelayField;
        
        private System.Nullable<byte> SingLampOpenClctDelayField;
        
        private System.Nullable<double> SlaCapFailEvtPFLimtValField;
        
        private System.Nullable<double> SlaCapFailEvtRecoPFLimtValField;
        
        private System.Nullable<byte> SlaFailEvtILimitValField;
        
        private System.Nullable<byte> SlaFailEvtIRecovValField;
        
        private System.Nullable<byte> SlaFuseErrEvtILimtValField;
        
        private System.Nullable<byte> SlaFuseErrEvtIRecoValField;
        
        private System.Nullable<byte> SlampLowILimtValField;
        
        private System.Nullable<byte> SlampLowIRecovValField;
        
        private System.Nullable<byte> SlampOverILRecovValField;
        
        private System.Nullable<byte> SlampOverILimtValField;
        
        private System.Nullable<int> SmartClctIntvalField;
        
        private string SpecialDayCtlMarkField;
        
        private string SvrAPNField;
        
        private string SvrDomainIpField;
        
        private int SvrPortField;
        
        private string TempCtlMarkField;
        
        private System.Nullable<byte> TmnCommErrTestIntvalField;
        
        private string WeekCtlMarkField;
        
        private string memoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AIClctIntval
        {
            get
            {
                return this.AIClctIntvalField;
            }
            set
            {
                this.AIClctIntvalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte AutoRouteTick
        {
            get
            {
                return this.AutoRouteTickField;
            }
            set
            {
                this.AutoRouteTickField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CTUChByte
        {
            get
            {
                return this.CTUChByteField;
            }
            set
            {
                this.CTUChByteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte CTUChNum
        {
            get
            {
                return this.CTUChNumField;
            }
            set
            {
                this.CTUChNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CTUCommAddr
        {
            get
            {
                return this.CTUCommAddrField;
            }
            set
            {
                this.CTUCommAddrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CTUID
        {
            get
            {
                return this.CTUIDField;
            }
            set
            {
                this.CTUIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CTUMacAddr
        {
            get
            {
                return this.CTUMacAddrField;
            }
            set
            {
                this.CTUMacAddrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CTUName
        {
            get
            {
                return this.CTUNameField;
            }
            set
            {
                this.CTUNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte CTUType
        {
            get
            {
                return this.CTUTypeField;
            }
            set
            {
                this.CTUTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CabID
        {
            get
            {
                return this.CabIDField;
            }
            set
            {
                this.CabIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> CtrlCloseDiv
        {
            get
            {
                return this.CtrlCloseDivField;
            }
            set
            {
                this.CtrlCloseDivField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CtrlLineValidFlag
        {
            get
            {
                return this.CtrlLineValidFlagField;
            }
            set
            {
                this.CtrlLineValidFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DIClctIntval
        {
            get
            {
                return this.DIClctIntvalField;
            }
            set
            {
                this.DIClctIntvalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> DeviceType
        {
            get
            {
                return this.DeviceTypeField;
            }
            set
            {
                this.DeviceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> DiAlarmTick
        {
            get
            {
                return this.DiAlarmTickField;
            }
            set
            {
                this.DiAlarmTickField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> DiUpdateTime
        {
            get
            {
                return this.DiUpdateTimeField;
            }
            set
            {
                this.DiUpdateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte EnergyEfficient
        {
            get
            {
                return this.EnergyEfficientField;
            }
            set
            {
                this.EnergyEfficientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte EnergyTimeType
        {
            get
            {
                return this.EnergyTimeTypeField;
            }
            set
            {
                this.EnergyTimeTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventAutoUploadFlag
        {
            get
            {
                return this.EventAutoUploadFlagField;
            }
            set
            {
                this.EventAutoUploadFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventImportanceFlag
        {
            get
            {
                return this.EventImportanceFlagField;
            }
            set
            {
                this.EventImportanceFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventRecValidFlag
        {
            get
            {
                return this.EventRecValidFlagField;
            }
            set
            {
                this.EventRecValidFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> EveryDayCtlMark
        {
            get
            {
                return this.EveryDayCtlMarkField;
            }
            set
            {
                this.EveryDayCtlMarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FSM
        {
            get
            {
                return this.FSMField;
            }
            set
            {
                this.FSMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> FindPTUTick
        {
            get
            {
                return this.FindPTUTickField;
            }
            set
            {
                this.FindPTUTickField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> GPRSHeart
        {
            get
            {
                return this.GPRSHeartField;
            }
            set
            {
                this.GPRSHeartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> GPRSRetryCount
        {
            get
            {
                return this.GPRSRetryCountField;
            }
            set
            {
                this.GPRSRetryCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GPRSTimeOut
        {
            get
            {
                return this.GPRSTimeOutField;
            }
            set
            {
                this.GPRSTimeOutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GSM_IMEI
        {
            get
            {
                return this.GSM_IMEIField;
            }
            set
            {
                this.GSM_IMEIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte HavePTUStatus
        {
            get
            {
                return this.HavePTUStatusField;
            }
            set
            {
                this.HavePTUStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> HaveRTU
        {
            get
            {
                return this.HaveRTUField;
            }
            set
            {
                this.HaveRTUField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAddress
        {
            get
            {
                return this.IPAddressField;
            }
            set
            {
                this.IPAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPGateway
        {
            get
            {
                return this.IPGatewayField;
            }
            set
            {
                this.IPGatewayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> IsNeedRpyMask
        {
            get
            {
                return this.IsNeedRpyMaskField;
            }
            set
            {
                this.IsNeedRpyMaskField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IsSingleLampFunc
        {
            get
            {
                return this.IsSingleLampFuncField;
            }
            set
            {
                this.IsSingleLampFuncField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LogPrintTick
        {
            get
            {
                return this.LogPrintTickField;
            }
            set
            {
                this.LogPrintTickField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MASKAddress
        {
            get
            {
                return this.MASKAddressField;
            }
            set
            {
                this.MASKAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePhoneNo
        {
            get
            {
                return this.MobilePhoneNoField;
            }
            set
            {
                this.MobilePhoneNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> NetworkType
        {
            get
            {
                return this.NetworkTypeField;
            }
            set
            {
                this.NetworkTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte PLCComTimer
        {
            get
            {
                return this.PLCComTimerField;
            }
            set
            {
                this.PLCComTimerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PTUCount
        {
            get
            {
                return this.PTUCountField;
            }
            set
            {
                this.PTUCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> PTUType
        {
            get
            {
                return this.PTUTypeField;
            }
            set
            {
                this.PTUTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> PollingTick
        {
            get
            {
                return this.PollingTickField;
            }
            set
            {
                this.PollingTickField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> PwrSaveSwitchMaxPos
        {
            get
            {
                return this.PwrSaveSwitchMaxPosField;
            }
            set
            {
                this.PwrSaveSwitchMaxPosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PwrSaveValidFlag
        {
            get
            {
                return this.PwrSaveValidFlagField;
            }
            set
            {
                this.PwrSaveValidFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> RouterCommErrTestIntval
        {
            get
            {
                return this.RouterCommErrTestIntvalField;
            }
            set
            {
                this.RouterCommErrTestIntvalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SIM_IMSI
        {
            get
            {
                return this.SIM_IMSIField;
            }
            set
            {
                this.SIM_IMSIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> SingLampCloseClctDelay
        {
            get
            {
                return this.SingLampCloseClctDelayField;
            }
            set
            {
                this.SingLampCloseClctDelayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> SingLampCurrClctDelay
        {
            get
            {
                return this.SingLampCurrClctDelayField;
            }
            set
            {
                this.SingLampCurrClctDelayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> SingLampOpenClctDelay
        {
            get
            {
                return this.SingLampOpenClctDelayField;
            }
            set
            {
                this.SingLampOpenClctDelayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> SlaCapFailEvtPFLimtVal
        {
            get
            {
                return this.SlaCapFailEvtPFLimtValField;
            }
            set
            {
                this.SlaCapFailEvtPFLimtValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> SlaCapFailEvtRecoPFLimtVal
        {
            get
            {
                return this.SlaCapFailEvtRecoPFLimtValField;
            }
            set
            {
                this.SlaCapFailEvtRecoPFLimtValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> SlaFailEvtILimitVal
        {
            get
            {
                return this.SlaFailEvtILimitValField;
            }
            set
            {
                this.SlaFailEvtILimitValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> SlaFailEvtIRecovVal
        {
            get
            {
                return this.SlaFailEvtIRecovValField;
            }
            set
            {
                this.SlaFailEvtIRecovValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> SlaFuseErrEvtILimtVal
        {
            get
            {
                return this.SlaFuseErrEvtILimtValField;
            }
            set
            {
                this.SlaFuseErrEvtILimtValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> SlaFuseErrEvtIRecoVal
        {
            get
            {
                return this.SlaFuseErrEvtIRecoValField;
            }
            set
            {
                this.SlaFuseErrEvtIRecoValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> SlampLowILimtVal
        {
            get
            {
                return this.SlampLowILimtValField;
            }
            set
            {
                this.SlampLowILimtValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> SlampLowIRecovVal
        {
            get
            {
                return this.SlampLowIRecovValField;
            }
            set
            {
                this.SlampLowIRecovValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> SlampOverILRecovVal
        {
            get
            {
                return this.SlampOverILRecovValField;
            }
            set
            {
                this.SlampOverILRecovValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> SlampOverILimtVal
        {
            get
            {
                return this.SlampOverILimtValField;
            }
            set
            {
                this.SlampOverILimtValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SmartClctIntval
        {
            get
            {
                return this.SmartClctIntvalField;
            }
            set
            {
                this.SmartClctIntvalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecialDayCtlMark
        {
            get
            {
                return this.SpecialDayCtlMarkField;
            }
            set
            {
                this.SpecialDayCtlMarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SvrAPN
        {
            get
            {
                return this.SvrAPNField;
            }
            set
            {
                this.SvrAPNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SvrDomainIp
        {
            get
            {
                return this.SvrDomainIpField;
            }
            set
            {
                this.SvrDomainIpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SvrPort
        {
            get
            {
                return this.SvrPortField;
            }
            set
            {
                this.SvrPortField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TempCtlMark
        {
            get
            {
                return this.TempCtlMarkField;
            }
            set
            {
                this.TempCtlMarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> TmnCommErrTestIntval
        {
            get
            {
                return this.TmnCommErrTestIntvalField;
            }
            set
            {
                this.TmnCommErrTestIntvalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WeekCtlMark
        {
            get
            {
                return this.WeekCtlMarkField;
            }
            set
            {
                this.WeekCtlMarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string memo
        {
            get
            {
                return this.memoField;
            }
            set
            {
                this.memoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tSysRunStatus", Namespace="http://schemas.datacontract.org/2004/07/LFCDal.Model")]
    public partial class tSysRunStatus : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CTUIDField;
        
        private System.Nullable<System.DateTime> EmgyCtrlEndTimeField;
        
        private System.Nullable<int> EmgyCtrlMaskField;
        
        private System.Nullable<int> EmgyCtrlValField;
        
        private System.Nullable<int> GPRSCSQField;
        
        private System.Nullable<int> GPRSTryConnTimesField;
        
        private System.Nullable<int> MainVerField;
        
        private System.Nullable<byte> PLCSatusField;
        
        private System.Nullable<System.DateTime> StartTimeField;
        
        private System.Nullable<int> SubVerField;
        
        private System.Nullable<byte> SvrStatusField;
        
        private System.Nullable<System.DateTime> UpdateTimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CTUID
        {
            get
            {
                return this.CTUIDField;
            }
            set
            {
                this.CTUIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EmgyCtrlEndTime
        {
            get
            {
                return this.EmgyCtrlEndTimeField;
            }
            set
            {
                this.EmgyCtrlEndTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EmgyCtrlMask
        {
            get
            {
                return this.EmgyCtrlMaskField;
            }
            set
            {
                this.EmgyCtrlMaskField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EmgyCtrlVal
        {
            get
            {
                return this.EmgyCtrlValField;
            }
            set
            {
                this.EmgyCtrlValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GPRSCSQ
        {
            get
            {
                return this.GPRSCSQField;
            }
            set
            {
                this.GPRSCSQField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GPRSTryConnTimes
        {
            get
            {
                return this.GPRSTryConnTimesField;
            }
            set
            {
                this.GPRSTryConnTimesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MainVer
        {
            get
            {
                return this.MainVerField;
            }
            set
            {
                this.MainVerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> PLCSatus
        {
            get
            {
                return this.PLCSatusField;
            }
            set
            {
                this.PLCSatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartTime
        {
            get
            {
                return this.StartTimeField;
            }
            set
            {
                this.StartTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SubVer
        {
            get
            {
                return this.SubVerField;
            }
            set
            {
                this.SubVerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> SvrStatus
        {
            get
            {
                return this.SvrStatusField;
            }
            set
            {
                this.SvrStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateTime
        {
            get
            {
                return this.UpdateTimeField;
            }
            set
            {
                this.UpdateTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vLampInfo", Namespace="http://schemas.datacontract.org/2004/07/LFCDal.Model")]
    public partial class vLampInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CTUCommAddrField;
        
        private string CtuIDField;
        
        private byte GrpNoField;
        
        private int LampNoField;
        
        private byte LampStatusField;
        
        private byte LampTypeField;
        
        private byte PtuChNoField;
        
        private string PtuIDField;
        
        private string PtuVerField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CTUCommAddr
        {
            get
            {
                return this.CTUCommAddrField;
            }
            set
            {
                this.CTUCommAddrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CtuID
        {
            get
            {
                return this.CtuIDField;
            }
            set
            {
                this.CtuIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte GrpNo
        {
            get
            {
                return this.GrpNoField;
            }
            set
            {
                this.GrpNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LampNo
        {
            get
            {
                return this.LampNoField;
            }
            set
            {
                this.LampNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte LampStatus
        {
            get
            {
                return this.LampStatusField;
            }
            set
            {
                this.LampStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte LampType
        {
            get
            {
                return this.LampTypeField;
            }
            set
            {
                this.LampTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte PtuChNo
        {
            get
            {
                return this.PtuChNoField;
            }
            set
            {
                this.PtuChNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PtuID
        {
            get
            {
                return this.PtuIDField;
            }
            set
            {
                this.PtuIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PtuVer
        {
            get
            {
                return this.PtuVerField;
            }
            set
            {
                this.PtuVerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tLampNewStatus", Namespace="http://schemas.datacontract.org/2004/07/LFCDal.Model")]
    public partial class tLampNewStatus : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime CDateTimeField;
        
        private string CTUIDField;
        
        private System.Nullable<byte> LampInsAlarmField;
        
        private int LampNoField;
        
        private byte LampStatusField;
        
        private System.Nullable<byte> LockStatusField;
        
        private System.Nullable<byte> OptByField;
        
        private System.Nullable<System.DateTime> OptDTimeField;
        
        private System.Nullable<byte> OptStatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CDateTime
        {
            get
            {
                return this.CDateTimeField;
            }
            set
            {
                this.CDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CTUID
        {
            get
            {
                return this.CTUIDField;
            }
            set
            {
                this.CTUIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> LampInsAlarm
        {
            get
            {
                return this.LampInsAlarmField;
            }
            set
            {
                this.LampInsAlarmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LampNo
        {
            get
            {
                return this.LampNoField;
            }
            set
            {
                this.LampNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte LampStatus
        {
            get
            {
                return this.LampStatusField;
            }
            set
            {
                this.LampStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> LockStatus
        {
            get
            {
                return this.LockStatusField;
            }
            set
            {
                this.LockStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> OptBy
        {
            get
            {
                return this.OptByField;
            }
            set
            {
                this.OptByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OptDTime
        {
            get
            {
                return this.OptDTimeField;
            }
            set
            {
                this.OptDTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> OptStatus
        {
            get
            {
                return this.OptStatusField;
            }
            set
            {
                this.OptStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tPTUCurDataRec", Namespace="http://schemas.datacontract.org/2004/07/LFCDal.Model")]
    public partial class tPTUCurDataRec : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CTUIDField;
        
        private System.Nullable<byte> CommValueField;
        
        private System.DateTime GetDateTimeField;
        
        private double LampAPField;
        
        private double LampIField;
        
        private System.Nullable<int> LampNoField;
        
        private double LampPFField;
        
        private System.Nullable<byte> LampStatusField;
        
        private System.Nullable<byte> LampStatus2Field;
        
        private double LampUField;
        
        private double LampVPField;
        
        private string MemoField;
        
        private System.Nullable<byte> OptByField;
        
        private System.Nullable<byte> OptStatusField;
        
        private byte PTUChNoField;
        
        private int PTUNoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CTUID
        {
            get
            {
                return this.CTUIDField;
            }
            set
            {
                this.CTUIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> CommValue
        {
            get
            {
                return this.CommValueField;
            }
            set
            {
                this.CommValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GetDateTime
        {
            get
            {
                return this.GetDateTimeField;
            }
            set
            {
                this.GetDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LampAP
        {
            get
            {
                return this.LampAPField;
            }
            set
            {
                this.LampAPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LampI
        {
            get
            {
                return this.LampIField;
            }
            set
            {
                this.LampIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LampNo
        {
            get
            {
                return this.LampNoField;
            }
            set
            {
                this.LampNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LampPF
        {
            get
            {
                return this.LampPFField;
            }
            set
            {
                this.LampPFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> LampStatus
        {
            get
            {
                return this.LampStatusField;
            }
            set
            {
                this.LampStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> LampStatus2
        {
            get
            {
                return this.LampStatus2Field;
            }
            set
            {
                this.LampStatus2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LampU
        {
            get
            {
                return this.LampUField;
            }
            set
            {
                this.LampUField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LampVP
        {
            get
            {
                return this.LampVPField;
            }
            set
            {
                this.LampVPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memo
        {
            get
            {
                return this.MemoField;
            }
            set
            {
                this.MemoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> OptBy
        {
            get
            {
                return this.OptByField;
            }
            set
            {
                this.OptByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> OptStatus
        {
            get
            {
                return this.OptStatusField;
            }
            set
            {
                this.OptStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte PTUChNo
        {
            get
            {
                return this.PTUChNoField;
            }
            set
            {
                this.PTUChNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PTUNo
        {
            get
            {
                return this.PTUNoField;
            }
            set
            {
                this.PTUNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tLampTmpCtrlCfg", Namespace="http://schemas.datacontract.org/2004/07/LFCDal.Model")]
    public partial class tLampTmpCtrlCfg : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CTUIDField;
        
        private int CfgNoField;
        
        private System.Nullable<byte> CtrlStatusField;
        
        private int LampObjNoField;
        
        private string MemoField;
        
        private System.Nullable<System.DateTime> OptDateTimeField;
        
        private byte OptTypeField;
        
        private byte OptValueField;
        
        private System.DateTime PlanOptDateTimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CTUID
        {
            get
            {
                return this.CTUIDField;
            }
            set
            {
                this.CTUIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CfgNo
        {
            get
            {
                return this.CfgNoField;
            }
            set
            {
                this.CfgNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> CtrlStatus
        {
            get
            {
                return this.CtrlStatusField;
            }
            set
            {
                this.CtrlStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LampObjNo
        {
            get
            {
                return this.LampObjNoField;
            }
            set
            {
                this.LampObjNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memo
        {
            get
            {
                return this.MemoField;
            }
            set
            {
                this.MemoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OptDateTime
        {
            get
            {
                return this.OptDateTimeField;
            }
            set
            {
                this.OptDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte OptType
        {
            get
            {
                return this.OptTypeField;
            }
            set
            {
                this.OptTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte OptValue
        {
            get
            {
                return this.OptValueField;
            }
            set
            {
                this.OptValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PlanOptDateTime
        {
            get
            {
                return this.PlanOptDateTimeField;
            }
            set
            {
                this.PlanOptDateTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="pLampTmpCtrlCfg", Namespace="http://schemas.datacontract.org/2004/07/LFCDal.Model")]
    public partial class pLampTmpCtrlCfg : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CmdTypeField;
        
        private int NoField;
        
        private int OptTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CmdType
        {
            get
            {
                return this.CmdTypeField;
            }
            set
            {
                this.CmdTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int No
        {
            get
            {
                return this.NoField;
            }
            set
            {
                this.NoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OptType
        {
            get
            {
                return this.OptTypeField;
            }
            set
            {
                this.OptTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tLampWeekCtrlCfg", Namespace="http://schemas.datacontract.org/2004/07/LFCDal.Model")]
    public partial class tLampWeekCtrlCfg : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CTUIDField;
        
        private byte CmdTypeField;
        
        private System.Nullable<byte> CtrlStatusField;
        
        private int GrpNoField;
        
        private System.Nullable<int> LampOrGrpNoField;
        
        private System.Nullable<System.DateTime> OptDateTimeField;
        
        private string OptTimeField;
        
        private System.Nullable<byte> OptTypeField;
        
        private System.Nullable<int> OptValueField;
        
        private System.Nullable<byte> TimeTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CTUID
        {
            get
            {
                return this.CTUIDField;
            }
            set
            {
                this.CTUIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte CmdType
        {
            get
            {
                return this.CmdTypeField;
            }
            set
            {
                this.CmdTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> CtrlStatus
        {
            get
            {
                return this.CtrlStatusField;
            }
            set
            {
                this.CtrlStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GrpNo
        {
            get
            {
                return this.GrpNoField;
            }
            set
            {
                this.GrpNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LampOrGrpNo
        {
            get
            {
                return this.LampOrGrpNoField;
            }
            set
            {
                this.LampOrGrpNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OptDateTime
        {
            get
            {
                return this.OptDateTimeField;
            }
            set
            {
                this.OptDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OptTime
        {
            get
            {
                return this.OptTimeField;
            }
            set
            {
                this.OptTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> OptType
        {
            get
            {
                return this.OptTypeField;
            }
            set
            {
                this.OptTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OptValue
        {
            get
            {
                return this.OptValueField;
            }
            set
            {
                this.OptValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> TimeType
        {
            get
            {
                return this.TimeTypeField;
            }
            set
            {
                this.TimeTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tCTUOCDayCfg", Namespace="http://schemas.datacontract.org/2004/07/LFCDal.Model")]
    public partial class tCTUOCDayCfg : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CTUIDField;
        
        private string CloseTimeField;
        
        private string OpenTimeField;
        
        private byte TMonthField;
        
        private byte TdayField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CTUID
        {
            get
            {
                return this.CTUIDField;
            }
            set
            {
                this.CTUIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CloseTime
        {
            get
            {
                return this.CloseTimeField;
            }
            set
            {
                this.CloseTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OpenTime
        {
            get
            {
                return this.OpenTimeField;
            }
            set
            {
                this.OpenTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte TMonth
        {
            get
            {
                return this.TMonthField;
            }
            set
            {
                this.TMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Tday
        {
            get
            {
                return this.TdayField;
            }
            set
            {
                this.TdayField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tLampHisDataRec", Namespace="http://schemas.datacontract.org/2004/07/LFCDal.Model")]
    public partial class tLampHisDataRec : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CTUIDField;
        
        private byte CommValueField;
        
        private System.DateTime GetDateTimeField;
        
        private double LampAPField;
        
        private int LampDataRecNoField;
        
        private double LampIField;
        
        private int LampNoField;
        
        private double LampPFField;
        
        private System.Nullable<byte> LampStatusField;
        
        private double LampUField;
        
        private double LampVPField;
        
        private string MemoField;
        
        private System.Nullable<System.DateTime> UpLoadDTimeField;
        
        private System.Nullable<byte> isUpLoadedField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CTUID
        {
            get
            {
                return this.CTUIDField;
            }
            set
            {
                this.CTUIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte CommValue
        {
            get
            {
                return this.CommValueField;
            }
            set
            {
                this.CommValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GetDateTime
        {
            get
            {
                return this.GetDateTimeField;
            }
            set
            {
                this.GetDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LampAP
        {
            get
            {
                return this.LampAPField;
            }
            set
            {
                this.LampAPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LampDataRecNo
        {
            get
            {
                return this.LampDataRecNoField;
            }
            set
            {
                this.LampDataRecNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LampI
        {
            get
            {
                return this.LampIField;
            }
            set
            {
                this.LampIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LampNo
        {
            get
            {
                return this.LampNoField;
            }
            set
            {
                this.LampNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LampPF
        {
            get
            {
                return this.LampPFField;
            }
            set
            {
                this.LampPFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> LampStatus
        {
            get
            {
                return this.LampStatusField;
            }
            set
            {
                this.LampStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LampU
        {
            get
            {
                return this.LampUField;
            }
            set
            {
                this.LampUField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LampVP
        {
            get
            {
                return this.LampVPField;
            }
            set
            {
                this.LampVPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memo
        {
            get
            {
                return this.MemoField;
            }
            set
            {
                this.MemoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpLoadDTime
        {
            get
            {
                return this.UpLoadDTimeField;
            }
            set
            {
                this.UpLoadDTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> isUpLoaded
        {
            get
            {
                return this.isUpLoadedField;
            }
            set
            {
                this.isUpLoadedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tLampGrpCfg", Namespace="http://schemas.datacontract.org/2004/07/LFCDal.Model")]
    public partial class tLampGrpCfg : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CTUIDField;
        
        private System.Nullable<System.DateTime> DLDateTimeField;
        
        private System.Nullable<byte> DLFailedTimesField;
        
        private System.Nullable<byte> DownloadTickField;
        
        private int GrpNoField;
        
        private int LampNoField;
        
        private System.Nullable<System.DateTime> OptDatetimeField;
        
        private System.Nullable<byte> OptTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CTUID
        {
            get
            {
                return this.CTUIDField;
            }
            set
            {
                this.CTUIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DLDateTime
        {
            get
            {
                return this.DLDateTimeField;
            }
            set
            {
                this.DLDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> DLFailedTimes
        {
            get
            {
                return this.DLFailedTimesField;
            }
            set
            {
                this.DLFailedTimesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> DownloadTick
        {
            get
            {
                return this.DownloadTickField;
            }
            set
            {
                this.DownloadTickField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GrpNo
        {
            get
            {
                return this.GrpNoField;
            }
            set
            {
                this.GrpNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LampNo
        {
            get
            {
                return this.LampNoField;
            }
            set
            {
                this.LampNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OptDatetime
        {
            get
            {
                return this.OptDatetimeField;
            }
            set
            {
                this.OptDatetimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> OptType
        {
            get
            {
                return this.OptTypeField;
            }
            set
            {
                this.OptTypeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDBDal")]
public interface IDBDal
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBDal/GetInfoByPara", ReplyAction="http://tempuri.org/IDBDal/GetInfoByParaResponse")]
    LFCDal.Utility.LFCDalParameter GetInfoByPara(LFCDal.Utility.LFCDalParameter para);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBDal/GetInfoByPara", ReplyAction="http://tempuri.org/IDBDal/GetInfoByParaResponse")]
    System.Threading.Tasks.Task<LFCDal.Utility.LFCDalParameter> GetInfoByParaAsync(LFCDal.Utility.LFCDalParameter para);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBDal/DelInfoByPara", ReplyAction="http://tempuri.org/IDBDal/DelInfoByParaResponse")]
    void DelInfoByPara(LFCDal.Utility.LFCDalParameter para);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBDal/DelInfoByPara", ReplyAction="http://tempuri.org/IDBDal/DelInfoByParaResponse")]
    System.Threading.Tasks.Task DelInfoByParaAsync(LFCDal.Utility.LFCDalParameter para);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBDal/AddInfoByPara", ReplyAction="http://tempuri.org/IDBDal/AddInfoByParaResponse")]
    void AddInfoByPara(LFCDal.Utility.LFCDalParameter para);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBDal/AddInfoByPara", ReplyAction="http://tempuri.org/IDBDal/AddInfoByParaResponse")]
    System.Threading.Tasks.Task AddInfoByParaAsync(LFCDal.Utility.LFCDalParameter para);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBDal/UpdateInfoByPara", ReplyAction="http://tempuri.org/IDBDal/UpdateInfoByParaResponse")]
    void UpdateInfoByPara(LFCDal.Utility.LFCDalParameter para);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBDal/UpdateInfoByPara", ReplyAction="http://tempuri.org/IDBDal/UpdateInfoByParaResponse")]
    System.Threading.Tasks.Task UpdateInfoByParaAsync(LFCDal.Utility.LFCDalParameter para);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBDal/GetInfo", ReplyAction="http://tempuri.org/IDBDal/GetInfoResponse")]
    LFCDal.Utility.LFCDalParameter GetInfo();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBDal/GetInfo", ReplyAction="http://tempuri.org/IDBDal/GetInfoResponse")]
    System.Threading.Tasks.Task<LFCDal.Utility.LFCDalParameter> GetInfoAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDBDalChannel : IDBDal, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DBDalClient : System.ServiceModel.ClientBase<IDBDal>, IDBDal
{
    
    public DBDalClient()
    {
    }
    
    public DBDalClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DBDalClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DBDalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DBDalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public LFCDal.Utility.LFCDalParameter GetInfoByPara(LFCDal.Utility.LFCDalParameter para)
    {
        return base.Channel.GetInfoByPara(para);
    }
    
    public System.Threading.Tasks.Task<LFCDal.Utility.LFCDalParameter> GetInfoByParaAsync(LFCDal.Utility.LFCDalParameter para)
    {
        return base.Channel.GetInfoByParaAsync(para);
    }
    
    public void DelInfoByPara(LFCDal.Utility.LFCDalParameter para)
    {
        base.Channel.DelInfoByPara(para);
    }
    
    public System.Threading.Tasks.Task DelInfoByParaAsync(LFCDal.Utility.LFCDalParameter para)
    {
        return base.Channel.DelInfoByParaAsync(para);
    }
    
    public void AddInfoByPara(LFCDal.Utility.LFCDalParameter para)
    {
        base.Channel.AddInfoByPara(para);
    }
    
    public System.Threading.Tasks.Task AddInfoByParaAsync(LFCDal.Utility.LFCDalParameter para)
    {
        return base.Channel.AddInfoByParaAsync(para);
    }
    
    public void UpdateInfoByPara(LFCDal.Utility.LFCDalParameter para)
    {
        base.Channel.UpdateInfoByPara(para);
    }
    
    public System.Threading.Tasks.Task UpdateInfoByParaAsync(LFCDal.Utility.LFCDalParameter para)
    {
        return base.Channel.UpdateInfoByParaAsync(para);
    }
    
    public LFCDal.Utility.LFCDalParameter GetInfo()
    {
        return base.Channel.GetInfo();
    }
    
    public System.Threading.Tasks.Task<LFCDal.Utility.LFCDalParameter> GetInfoAsync()
    {
        return base.Channel.GetInfoAsync();
    }
}
